export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';

export const FETCH_LOCATION_LOADING = 'FETCH_LOCATION_LOADING';

export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';

export const SET_ZIP_CODE = 'SET_ZIP_CODE';

export const SET_SELECTION = 'SET_SELECTION';
